apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: chat-frontend
          image: tavigingu/chat-frontend:v7
          ports:
            - containerPort: 90
      #     volumeMounts:
      #       - name: config-volume
      #         mountPath: /usr/share/nginx/html/config
      # volumes:
      #   - name: config-volume
      #     configMap:
      #       name: chat-frontend-config
      #       items:
      #         - key: config.json
      #           path: config.json
---

