apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-frontend-config
  namespace: default
data:
  config.json: |
    {
      "production": false,
      "apiUrl": "http://localhost:30090/api",
      "wsUrl": "ws://localhost:30090/ws"
    }
