apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-service
  namespace: default
spec:
  selector:
    app: chat-frontend
  ports:
    - port: 90
      targetPort: 90
      nodePort: 30090
  type: NodePort