apiVersion: v1
kind: Service
metadata:
  name: chat-backend
  namespace: default
spec:
  selector:
    app: chat-backend
  ports:
    - port: 8080
      targetPort: 88
      protocol: TCP
      name: http-websocket
  type: ClusterIP
  
