apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  namespace: default
spec:
  replicas: 6
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
        - name: chat-backend
          image: tavigingu/chat-backend:v1
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: chat-backend-config
                  key: MONGO_URI
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: chat-backend-config
                  key: DB_NAME
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: chat-backend-config
                  key: SERVER_PORT
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
