version: "3.8"
services:
  joomla:
    image: joomla:latest
    ports:
      - "8088:80"
    environment:
      - JOOMLA_DB_HOST=mysql-service
      - JOOMLA_DB_USER=joomla_user
      - JOOMLA_DB_PASSWORD=joomla_pass
      - JOOMLA_DB_NAME=joomla_db
    depends_on:
      - db
    volumes:
      - ./joomla_dat_new:/var/www/html

  db:
    image: mysql:8.0.13
    container_name: mysql-service
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_USER=joomla_user
      - MYSQL_PASSWORD=joomla_pass
      - MYSQL_DATABASE=joomla_db
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
