FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM nginx:alpine


# Copiem executabilul Go compilat
COPY --from=builder /app/main /usr/local/bin/main

# Copiem configurația Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expunem portul 88
EXPOSE 88

CMD ["sh", "-c", "nginx & /usr/local/bin/main"]