FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

# copiem cod sursa
COPY . .

# Compilăm aplicația
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd

FROM nginx:alpine

# Copiem executabilul Go compilat
COPY --from=builder /app/main /usr/local/bin/main

# Copiem configurația  nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 99

CMD ["sh", "-c", "nginx & /usr/local/bin/main"]