# Etapa 1: Construirea aplicației Angular
FROM node:20-alpine AS build

WORKDIR /app

# Copiem package.json și package-lock.json
COPY package*.json ./

# Instalăm dependențele
RUN npm install

# Copiem restul aplicației
COPY . .

RUN mkdir -p src/environments

RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/frontend-angular/browser /usr/share/nginx/html

# Expunem portul 98
EXPOSE 98

CMD ["nginx", "-g", "daemon off;"]