apiVersion: v1
kind: Service
metadata:
  name: text-backend
  namespace: default
spec:
  selector:
    app: text-backend
  ports:
    - port: 99
      targetPort: 99
      protocol: TCP
      name: http
  type: ClusterIP
