apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
stringData:
  AZURE_BLOB_ACCOUNT_NAME: aiproiectstorage
  AZURE_BLOB_ACCOUNT_KEY: lkGR2Ge3nyM37LTayu+/UPxl/hujO7alwqCasw/u9o03eKt7olW3fnnzCX4mstJCYAjV0FhiH0td+AStnEn5PA==
  AZURE_BLOB_CONTAINER_NAME: storage-container
  AZURE_SQL_SERVER_NAME: text-processing-server
  AZURE_SQL_DB_NAME: text-processing-db
  AZURE_SQL_USERNAME: admindb
  AZURE_SQL_PASSWORD: 30februariE
  AZURE_COGNITIVE_SERVICES_ENDPOINT: https://entityextraction.cognitiveservices.azure.com
  AZURE_COGNITIVE_SERVICES_KEY: 5oH9mN96M5AfcrAEd3qugKsGF8H1ARyAmWFpQIMGoyanZOLtX2xB0JQQJ99BDACPV0roXJ3w3AAAaACOGm4f4