apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-frontend
  template:
    metadata:
      labels:
        app: text-frontend
    spec:
      containers:
        - name: text-frontend
          image: tavigingu/text-frontend:v18
          ports:
            - containerPort: 98
          # env:
          #   - name: API_URL
          #     value: "http://text-backend:99/api" # Point to backend service
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
